Feature branche
kerlos-bahaa/Hello-Microverse-project pull request #2
Opened 2023-02-15 15:00 UTC by kerlos-bahaa

* We did fixes as mentioned in the previous Pull request 
Link: https://github.com/kerlos-bahaa/Hello-Microverse-project/pull/1
-------------------------------------------------------------------------------------------------------------------------
1- Add an HTML file with Hello Microverse! as a header

2- Add a CSS file with a color class for the header

3- Add .gitignore with node_modules and test.md included

4- Add the readme file to the project

5- Add a linter for HTML and CSS

2023-02-15 15:17 UTC, roshan-bajgain requested changes
Hi @kerlos-bahaa, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

 ## Required Changes ♻️
- [ ] You can name your pull request title `Hello Microverse`. Please do so in place of feature branch.
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 15:17 UTC, roshan-bajgain commented on README.md
> +**[your_project__name]** is a...
- [ ] As requested by previous reviewer please name the project and add 1,2 line description on it for professional README.

2023-02-15 15:17 UTC, roshan-bajgain commented on README.md
> +
- [ ] Please remove other and use HTML and CSS as this project is made from HTML and CSS.

2023-02-15 15:17 UTC, roshan-bajgain commented on README.md
> +
- [ ] I would suggest you please add key feature you have on the project.

2023-02-15 15:17 UTC, roshan-bajgain commented on README.md
> +To get a local copy up and running, follow these steps.
- [ ] You can write a command on how the user can clone your project and open it in the browser. Like `git clone your url` and open through `live-server`

2023-02-15 15:17 UTC, roshan-bajgain commented on README.md
> +
- [ ] In this author section please use your details of Github, Twitter and LinkedIn so any user can visit your profile.

2023-02-15 15:17 UTC, roshan-bajgain commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] This license is broken please fix it. There is a link on how to create an MIT license. [link](https://choosealicense.com/licenses/mit/). [Link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

2023-02-16 23:05 UTC, Shisui6 approved these changes
Hi @kerlos-bahaa , 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 17:13 UTC, merged